#!/bin/zsh
set -euo pipefail

if (( $# < 1 || $# > 2 )); then
  print -u2 "Usage: Scripts/extract_release_notes.sh <version> [output-path]"
  exit 64
fi

VERSION="${1#v}"
OUTPUT_PATH="${2:-}"

if [[ ! "$VERSION" =~ '^[0-9]+(\.[0-9]+){1,3}$' ]]; then
  print -u2 "Version must contain 2 to 4 dot-separated numeric components (for example, 0.3.0)."
  exit 64
fi

ROOT_DIR="${0:A:h:h}"
CHANGELOG_PATH="$ROOT_DIR/CHANGELOG.md"
SECTION_PATH="$(mktemp "${TMPDIR:-/tmp}/notch-release-section.XXXXXX")"
NOTES_PATH="$(mktemp "${TMPDIR:-/tmp}/notch-release-notes.XXXXXX")"

cleanup() {
  rm -f "$SECTION_PATH" "$NOTES_PATH"
}
trap cleanup EXIT

if ! awk -v version="$VERSION" '
  BEGIN {
    target = "## [" version "]"
    capturing = 0
    found = 0
  }
  index($0, target) == 1 {
    suffix = substr($0, length(target) + 1)
    if (suffix == "" || suffix ~ /^[[:space:]]/) {
      capturing = 1
      found = 1
    }
  }
  capturing && $0 ~ /^## \[/ && index($0, target) != 1 {
    exit
  }
  capturing {
    print
  }
  END {
    if (!found) {
      exit 2
    }
  }
' "$CHANGELOG_PATH" > "$SECTION_PATH"; then
  print -u2 "CHANGELOG.md does not contain a release section for version $VERSION."
  exit 65
fi

if [[ ! -s "$SECTION_PATH" ]]; then
  print -u2 "The release section for version $VERSION is empty."
  exit 65
fi

if ! awk '
  /^###[[:space:]]+/ {
    heading = tolower($0)
    if (heading ~ /added/ || index($0, "新增") > 0) {
      group = "added"
      saw_added = 1
    } else if (heading ~ /fixed/ || index($0, "修复") > 0) {
      group = "fixed"
      saw_fixed = 1
    } else {
      group = ""
    }
    next
  }
  /^[[:space:]]*([-*+]|[0-9]+\.)[[:space:]]+[^[:space:]]/ {
    if (group == "added") {
      added_items++
    } else if (group == "fixed") {
      fixed_items++
    }
  }
  END {
    if (!saw_added || added_items < 1 || !saw_fixed || fixed_items < 1) {
      exit 1
    }
  }
' "$SECTION_PATH"; then
  print -u2 "Release $VERSION must contain non-empty Added/新增 and Fixed/修复 groups."
  exit 65
fi

if awk '
  tolower($0) ~ /full[[:space:]]+changelog/ || index($0, "完整变更日志") > 0 {
    found = 1
  }
  END {
    exit(found ? 0 : 1)
  }
' "$SECTION_PATH"; then
  print -u2 "Release $VERSION contains an autogenerated comparison footer; replace it with curated notes."
  exit 65
fi

{
  print "> **Manual installation / 手动安装：** Open the DMG, drag Notch Calendar to Applications, then relaunch it. Automatic app replacement remains disabled in this release. / 打开 DMG，将 Notch Calendar 拖入“应用程序”，然后重新启动；此版本仍未启用自动替换安装。"
  print
  cat "$SECTION_PATH"
} > "$NOTES_PATH"

if [[ -n "$OUTPUT_PATH" ]]; then
  OUTPUT_DIR="${OUTPUT_PATH:h}"
  mkdir -p "$OUTPUT_DIR"
  cp "$NOTES_PATH" "$OUTPUT_PATH"
else
  cat "$NOTES_PATH"
fi
